### ISSUE TITLE
DM Binlog 999999 keeps failing

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/ticdc#3283] opened 2021-11-04 15:34 UTC
### Which jobs are flaking?

DM Binlog 999999 

### Which test(s) are flaking?

 dmctl test cmd: "start-task /tmp/dm_test/incremental_mode/dm-task.yaml "

### Jenkins logs or GitHub Actions link

```log
check diff failed 10-th time, retry later
check diff failed at last
Error: unknown keys in config file /home/runner/work/ticdc/ticdc/dm/tests/incremental_mode/conf/diff_config.toml: [log-level chunk-size sample-percent use-checksum fix-sql-file check-tables check-tables.schema check-tables.tables table-config table-config.schema table-config.table table-config.source-tables table-config.source-tables.instance-id table-config.source-tables.schema table-config.source-tables.table table-config table-config.schema table-config.table table-config.source-tables table-config.source-tables.instance-id table-config.source-tables.schema table-config.source-tables.table source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id target-db target-db.host target-db.port target-db.user target-db.password]
  -V, --version                  print version of sync_diff_inspector
  -L, --log-level string         log level: debug, info, warn, error, fatal (default "info")
  -C, --config string            Config file
      --dm-addr string           the address of DM
      --dm-task string           identifier of dm task
      --check-thread-count int   how many goroutines are created to check data (default 1)
      --export-fix-sql           set true if want to compare rows or set to false will only compare checksum (default true)
      --check-struct-only        ignore check table's data
...
```

https://github.com/pingcap/ticdc/runs/4099248345?check_suite_focus=true

### Anything else we need to know

- Does this test exist for other branches as well?
No
- Has there been a high frequency of failure lately?
From yesterday keeps failing.

**Comment by hi-rustin** [comment] 2021-11-04 15:35
cc @lance6716 @GMHDBJD 

Could you please take a look? Thanks!  💚 💙 💜 💛 ❤️

**Comment by lance6716** [comment] 2021-11-04 15:41
> cc @lance6716 @GMHDBJD
> 
> Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

seems caused by sync-diff changed its configuration file. will try updating it tomorrow

**Comment by lance6716** [comment] 2021-11-05 02:11
we're using nightly sync_diff, but the config file for sync_diff is not ready. should be fixed by https://github.com/pingcap/ticdc/pull/3247

**Closed** 2021-11-08 04:55 UTC
Labels: component/test, area/dm
