### ISSUE TITLE
kafka changefeed was stuck after upgrading v4.0.13 to v4.0.14

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2404] opened 2021-07-29 06:16 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 2x capture, 2x changefeed. two cf works well in v4.0.13
  
![image](https://user-images.githubusercontent.com/78345569/127440401-aa22a14f-fc64-4b44-a596-cc930d190480.png)

- Load data to upgrade tidb: $ ./bin/go-ycsb load mysql -P ./workloads/oncall2929 -p mysql.host=172.16.6.24 -p mysql.port=4000 -p operationcount=5000000 -p autocommit=1 --threads=100 -p databasename=test123 -p tablename=test1

- Upgrade tidb cluster + capture to v4.0.14, check tiup cluster audit log:
  fGdfx9S2Yn0:2021-07-28T20:02:01.498+0800        INFO    Execute command {"command": "tiup cluster upgrade 360UP v4.0.14"}

- After upgrading successfully finished, check all captures started:
![image](https://user-images.githubusercontent.com/78345569/127441017-08e4e84f-7bcd-4a65-b95c-2641fda952b8.png)
![image](https://user-images.githubusercontent.com/78345569/127441093-df5f58c9-cb98-4ded-a70a-e82604cafedb.png)

- Check the two cf status after 12hours.

2. What did you expect to see?

- The two cf checkpoint is the latest datetime.

3. What did you see instead?

- sink-uri=kafka changefeed was stuck, while sink-uri=tidb changefeed is always normal.
![image](https://user-images.githubusercontent.com/78345569/127440141-37850c99-050e-4934-bffd-2557146c5f99.png)

- cdc ERROR log:
![image](https://user-images.githubusercontent.com/78345569/127440029-6e205a87-6a75-41c7-8b1a-7d73cc6fc530.png)
![image](https://user-images.githubusercontent.com/78345569/127440694-00109aa9-33ec-47a6-b52a-35a6a7f2de52.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.13GA --> 4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.13GA --> 4.0.14
        ```

**Comment by Tammyxia** [comment] 2021-07-29 07:29
cdc and tikv log has been uploaded to qa-minio/nfs/CDC_issue_log/CDC_issue_log/2404

**Comment by liuzix** [comment] 2021-07-29 10:55
The problem was caused by a partition that belonged to a dropped table being added to orphan table. The bug fixed in #2205 caused a partition to be replicated by two captures, and when the table was dropped, the partition was only deleted in one capture.

When an upgrade was performed, the owner added the partition to `orphanTables`, while in fact the partition had long been dropped. This caused unexpected behavior when the owner tried to find the partition's name in its schema snapshot. Hence, the owner was stuck.

`[2021/07/28 20:02:29.618 +08:00] [WARN] [changefeed.go:349] ["balance orphan tables delay, table not found"] [changefeed=kafka-task-23] [tableID=3713]`

**Comment by overvenus** [comment] 2021-07-30 12:37
Set severity/moderate as the issue is caused by a fixed bug.

**Closed** 2021-08-05 09:27 UTC
Labels: severity/moderate, type/bug
