### ISSUE TITLE
cdc binary exit with panic error

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1568] opened 2021-03-29 06:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Start  CDC server with binary version on two VMs: cdc server --pd=http://ip:2379 --advertise-addr=ip:8300 --addr=0.0.0.0:8300 --log-file=cdc.log --sort-dir=/tmp/cdc
- Delete the existed changfeed.
- Create new changfeed named "replication-task-8"
- 
2. What did you expect to see?

3. What did you see instead?
Slave CDC capture exit with PANIC log:
- 
![image](https://user-images.githubusercontent.com/78345569/112792325-d56ab880-9095-11eb-90d5-38cf5a47934c.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
      Release Version: v5.0.0
      Edition: Community
      Git Commit Hash: b18eae98087148ad967d7fcbf6586ed7b9607c4b
      Git Branch: heads/refs/tags/v5.0.0
      UTC Build Time: 2021-03-24 15:31:59
      GoVersion: go1.13
      Race Enabled: false
     TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
     Check Table Before Drop: false |
        ```

    - TiCDC version (execute `cdc version`):

        ```
       [release-version=v5.0.0-nightly-14-gadcc9c6] [git-hash=adcc9c6faf3d84fecd51739219304c747ee93add] [git-branch=release-5.0] [utc-build-time="2021-03-27 06:44:14"] [go-version="go version go1.13 linux/amd64"]
        ```

**Comment by amyangfei** [comment] 2021-05-25 09:33
can't reproduce

**Comment by lonng** [comment] 2021-05-27 08:52
I have changed the severity from critical to major because we can't reproduce this bug currently. And we need more information.

**Comment by amyangfei** [comment] 2021-12-08 07:50
KV client has migrated to v2, ref: https://github.com/pingcap/ticdc/issues/1393
This bug doesn't happen again. Close it now, if it happens again, feel free to reopen it.

**Closed by amyangfei** 2021-12-08 07:50 UTC
Labels: type/bug, severity/major, subject/replication-interruption, bug-from-internal-test, area/ticdc
