### ISSUE TITLE
unstable unit test, invalid memory address or nil pointer dereference in kv client test

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2347] opened 2021-07-22 03:17 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
[2021-07-21T11:02:44.948Z] [2021/07/21 19:01:55.286 +08:00] [ERROR] [client.go:1273] ["failed to receive from stream"] [addr=127.0.0.1:33385] [storeID=1] [error="injected error"] [errorVerbose="injected error\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStream\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:1262\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:856\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStream\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:1273\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:856\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-07-21T11:02:44.948Z] [2021/07/21 19:01:59.876 +08:00] [ERROR] [client_v2.go:219] ["failed to receive from stream"] [addr=127.0.0.1:46559] [storeID=1] [error="injected error"] [errorVerbose="injected error\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStreamV2\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go:208\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:858\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStreamV2\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go:219\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:858\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-07-21T11:02:44.948Z] [2021/07/21 19:02:05.279 +08:00] [ERROR] [client.go:1273] ["failed to receive from stream"] [addr=127.0.0.1:43038] [storeID=1] [error="injected stream recv error"] [errorVerbose="injected stream recv error\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStream\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:1262\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:856\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStream\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:1273\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:856\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-07-21T11:02:44.948Z] [2021/07/21 19:02:07.450 +08:00] [ERROR] [region_worker.go:645] ["The CommitTs must be greater than the resolvedTs"] ["Event Type"=COMMIT] [CommitTs=98] [resolvedTs=100] [regionID=3] [stack="github.com/pingcap/ticdc/cdc/kv.(*regionWorker).handleEventEntry\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:645\ngithub.com/pingcap/ticdc/cdc/kv.(*regionWorker).processEvent\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:352\ngithub.com/pingcap/ticdc/cdc/kv.(*regionWorker).eventHandler\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:449\ngithub.com/pingcap/ticdc/cdc/kv.(*regionWorker).run.func3\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:564\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-07-21T11:02:44.949Z] [2021/07/21 19:02:08.157 +08:00] [ERROR] [region_worker.go:626] ["The CommitTs must be greater than the resolvedTs"] ["Event Type"=COMMITTED] [CommitTs=98] [resolvedTs=100] [regionID=3] [stack="github.com/pingcap/ticdc/cdc/kv.(*regionWorker).handleEventEntry\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:626\ngithub.com/pingcap/ticdc/cdc/kv.(*regionWorker).processEvent\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:352\ngithub.com/pingcap/ticdc/cdc/kv.(*regionWorker).eventHandler\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:449\ngithub.com/pingcap/ticdc/cdc/kv.(*regionWorker).run.func3\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/region_worker.go:564\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-07-21T11:02:44.949Z] [2021/07/21 19:02:09.037 +08:00] [ERROR] [client.go:1180] ["tikv reported compatibility error, which is not expected"] [rpcCtx="region ID: 3, meta: id:3 peers:<id:4 store_id:1 > , peer: id:4 store_id:1 , addr: 127.0.0.1:40682, idx: 0, reqStoreType: TiKvOnly, runStoreType: tikv"] [error="required_version:\"v4.0.7\" "] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).handleError\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:1180\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func4\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:641\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-07-21T11:02:44.949Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-07-21T11:02:44.949Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19ebb8d]
[2021-07-21T11:02:44.949Z] 
[2021-07-21T11:02:44.949Z] goroutine 1390 [running]:
[2021-07-21T11:02:44.949Z] google.golang.org/grpc.(*ClientConn).NewStream(0x0, 0x61df350, 0xc000f9c4c0, 0x78aec40, 0x5004aee, 0x1b, 0x0, 0x0, 0x0, 0x0, ...)
[2021-07-21T11:02:44.949Z] 	/nfs/cache/mod/google.golang.org/grpc@v1.27.1/stream.go:145 +0x4d
[2021-07-21T11:02:44.949Z] github.com/pingcap/kvproto/pkg/cdcpb.(*changeDataClient).EventFeed(0xc0007489a8, 0x61df350, 0xc000f9c4c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x61931a0, 0xc000f4a5f0)
[2021-07-21T11:02:44.949Z] 	/nfs/cache/mod/github.com/pingcap/kvproto@v0.0.0-20210611081648-a215b4e61d2f/pkg/cdcpb/cdcpb.pb.go:1424 +0xfe
[2021-07-21T11:02:44.949Z] github.com/pingcap/ticdc/cdc/kv.(*CDCClient).newStream.func1(0xc000748f08, 0xc000748eb0)
[2021-07-21T11:02:44.949Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:465 +0x985
[2021-07-21T11:02:44.949Z] github.com/pingcap/ticdc/pkg/retry.run(0x61df350, 0xc000f9c4c0, 0xc000749090, 0xc0015a1880, 0x0, 0x0)
[2021-07-21T11:02:44.949Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/pkg/retry/retry_with_opt.go:54 +0xad
[2021-07-21T11:02:44.949Z] github.com/pingcap/ticdc/pkg/retry.Do(0x61df350, 0xc000f9c4c0, 0xc000a55090, 0xc000a55070, 0x4, 0x4, 0x4c87360, 0x61b7801)
[2021-07-21T11:02:44.949Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/pkg/retry/retry_with_opt.go:32 +0x73
[2021-07-21T11:02:44.949Z] github.com/pingcap/ticdc/cdc/kv.(*CDCClient).newStream(0xc000dd8320, 0x61df350, 0xc000f9c4c0, 0x4fd2190, 0xb, 0x1, 0x0, 0x0, 0x3a, 0x11d9498)
[2021-07-21T11:02:44.949Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:449 +0x1cd
[2021-07-21T11:02:44.949Z] github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore(0xc000540ea0, 0x61df350, 0xc000f9c400, 0xc000aa32c0, 0xc0015c5500, 0x0)
[2021-07-21T11:02:44.949Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:824 +0x243b
[2021-07-21T11:02:44.949Z] github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func2(0xc0002c3750, 0xc00047d200)
[2021-07-21T11:02:44.949Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:609 +0xa5
[2021-07-21T11:02:44.949Z] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000aa32c0, 0xc000aa3320)
[2021-07-21T11:02:44.949Z] 	/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x95
[2021-07-21T11:02:44.950Z] created by golang.org/x/sync/errgroup.(*Group).Go
[2021-07-21T11:02:44.950Z] 	/nfs/cache/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x74
[2021-07-21T11:02:44.950Z] FAIL	github.com/pingcap/ticdc/cdc/kv	25.119s
```

2. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/675aea7ad8045298ac88dad5913845c363c53326

**Comment by hi-rustin** [comment] 2021-07-30 03:14
Unable to reproduce this problem locally, has anyone else encountered this error recently?

**Comment by hi-rustin** [comment] 2021-09-08 10:42
/close 

I have run it many times with local restricted resources and could not reproduce the issue. So close it off for now. If you encounter this problem again please feel free to reopen this issue.

**Closed by hi-rustin** 2021-09-08 10:42 UTC
Labels: type/bug, component/test, severity/major

**Comment by amyangfei** [comment] 2021-09-08 10:46
Recently we met another strange panic in https://github.com/pingcap/ticdc/issues/2770, I suspect it a gRPC or go runtime bug, but doesn't have any more idea. @hi-rustin
