### ISSUE TITLE
cdc can not work if captures have different version deployed

### ISSUE THREAD

**Issue by ben1009** [pingcap/ticdc#2364] opened 2021-07-23 10:22 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
deploy two different versions to two captures
2. What did you expect to see?
do not deploy success at the beginning
3. What did you see instead?
can not replica data, can not remove changefeed, but no error reported from cli
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0
        ```

    - TiCDC version (execute `cdc version`):
       one with
        ```
        Release Version: v5.0.0
        Git Commit Hash: 39c1bd9ba9c3ab0e704d03a58df0360501e9f3bd
        Git Branch: release-5.0
        UTC Build Time: 2021-04-07 06:11:14
       Go Version: go version go1.13 linux/amd64
        ```
        another compiled by developer base on the same version

**Comment by ben1009** [comment] 2021-07-23 10:24
```
[2021/07/23 18:22:17.471 +08:00] [WARN] [owner.go:258] ["the capture version is different with the owner"] [capture="{\"id\":\"1b2d1ff5-7da7-45c0-bb9e-ec234193ee01\",\"address\":\"172.16.6.114:18304\",\"version\":\"v5.0.0\"}"] [my-version=v5.0.0-master-dirty]
[2021/07/23 18:22:18.472 +08:00] [WARN] [owner.go:258] ["the capture version is different with the owner"] [capture="{\"id\":\"1b2d1ff5-7da7-45c0-bb9e-ec234193ee01\",\"address\":\"172.16.6.114:18304\",\"version\":\"v5.0.0\"}"] [my-version=v5.0.0-master-dirty]
[2021/07/23 18:22:19.474 +08:00] [WARN] [owner.go:258] ["the capture version is different with the owner"] [capture="{\"id\":\"1b2d1ff5-7da7-45c0-bb9e-ec234193ee01\",\"address\":\"172.16.6.114:18304\",\"version\":\"v5.0.0\"}"] [my-version=v5.0.0-master-dirty]
```

**Comment by overvenus** [comment] 2021-07-26 05:55
What do you think @leoppro ?

**Comment by leoppro** [comment] 2021-08-24 08:34
it's by design, when the TiCDC cluster is upgraded, the version numbers of different nodes will be inconsistent for a short period of time, and we want to avoid the undefined behavior caused by this inconsistency

**Closed by leoppro** 2021-08-24 08:34 UTC
Labels: type/bug, component/replica-model, difficulty/easy, severity/moderate, bug-from-internal-test
