### ISSUE TITLE
openprotocol changed value behavior compatible with new collation

### ISSUE THREAD

**Issue by pepezzzz** [pingcap/ticdc#2073] opened 2021-06-16 22:51 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

In the default configuration, the Row Changed Event of TiCDC Open Protocol output in a replication task only contains the changed value, not the value before the change. Therefore, the output value neither supports the new collation framework introduced in TiDB v4.0 .

Enduser already build some flink application handling downstream openprotocol format data with enable-old-value = false. If these applications move to a TiDB cluster downstream with new collation enabled，that will make a compatible issue. Flink application can not deal with the p column properly which comes from enable-old-value , but TiCDC in TiDB cluster with new collation enabled always create enable-old-value task.

**Describe the feature you'd like:**

the search old value procedure always included by ticdc task，enable-old-value  configuration only control the old value output behavior not the search behavior. Then ,this configuration can compatible with new collation.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by amyangfei** [comment] 2021-06-17 01:58
I'm not quite understand the requirement, do you mean we should add another old-value switch, which can turn on old-value when receiving data from TiKV, and turn off the old-value output field in the open protocol

Besides `enable-old-value` is controlled in changefeed config, even for a upstream with new CI collation enabled, the `old-value` feature can be turned off (expect for two scenarios, `canal` and `maxwell` will enable old value by default, even the `enable-old-value` is false in the changefeed config)

**Comment by hi-rustin** [comment] 2021-08-18 06:02
Duplicate of https://github.com/pingcap/ticdc/issues/2301

**Closed** 2021-08-18 06:02 UTC
Labels: subject/new-feature
