### ISSUE TITLE
[TiCDC 5.3.0] sync task performance slower than 5.2.2

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#3430] opened 2021-11-12 03:16 UTC
### What did you do?

- Test infra case:basic_incremental_sync
     downstream is tidb

- create a changefeed, then stop it.
- run workload tpcc 20 warehouse:  /go-tpc tpcc
--db workload --warehouses 20 -T 20 --host upstream-tidb.cdc-testbed--tps-360688-1-582 --port 4000 --parts 1 prepare
  this command takes 3 minutes to complete.
- resume the changefeed, then run workload:/go-tpc tpcc
--db workload --warehouses 20 -T 20 --host upstream-tidb.cdc-testbed--tps-360688-1-582 --port 4000 --parts 1 --time 30m0s run

- waiting for sync task completing in 30 minutes 

### What did you expect to see?

Case successfully

### What did you see instead?

Case failed, because sync task cannot finish in 30m. Exceed about 3 minutes.
There's not any capture restart, nor changefeed stopped for abnormal.
Previously, this case daily run on master version, always passed.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
TiKV 
Release Version:   5.3.0-alpha
Edition:           Community
Git Commit Hash:   e16bf9c0f86d26fd41335f9714adbdd387862ee7
Git Commit Branch: heads/refs/tags/v5.3.0
UTC Build Time:    2021-11-11 10:03:53
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release```

TiCDC version (execute `cdc version`):

```
cdc
Release Version: v5.3.0
Git Commit Hash: dab50516592248e7eecd7678047f9fd958b09470
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-11 11:16:35
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false```

**Comment by Tammyxia** [comment] 2021-11-12 05:59
![image](https://user-images.githubusercontent.com/78345569/141406114-6a1ad97e-23f2-4f72-91e9-23bae0e481e0.png)
changefeed resumed in 3:18,  sync task taken 1 hour to complete with the above mentioned workload.

**Comment by Tammyxia** [comment] 2021-11-15 05:27
5.2.2 test result: 
![image](https://user-images.githubusercontent.com/78345569/141727267-9f77ef18-c780-4130-a11b-9b28b1016a0c.png)

**Comment by amyangfei** [comment] 2021-11-18 07:00
In TiCDC 5.3 and TiKV 5.3, replication 270G data (two cdc nodes) costs 1hour 3mins
In TiCDC 5.2 and TiKV 5.2, replication 270G data (two cdc nodes) costs 54mins 30secs

The regression is 15.6%.
But the boundary is to replicate 100G less than 3hours, performance doesn't exceed boundary.

**Comment by amyangfei** [comment] 2021-11-18 07:02
Close this issue since the performance regression is acceptable.

**Closed by amyangfei** 2021-11-18 07:02 UTC
Labels: type/bug, severity/major, found/automation, area/ticdc
