### ISSUE TITLE
endless log 'region not found on incremental scan' of tikv

### ISSUE THREAD

**Issue by july2993** [pingcap/ticdc#268] opened 2020-02-19 03:58 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1. sh tests/run.sh --debug   
2. sysbench load some data at upstream.

2. What did you expect to see?
replication works normally.

3. What did you see instead?
stop replicate after some time (no more data at down stream).

log of tikv.log continues printing   (even after stop cdc server means we can make sure no any more request to tikv)
endless retry of tikv?
```
[2020/02/19 11:48:13.256 +08:00] [WARN] [endpoint.rs:255] ["region not found on incremental scan"] [region_id=48]
[2020/02/19 11:48:13.256 +08:00] [WARN] [endpoint.rs:255] ["region not found on incremental scan"] [region_id=48]
[2020/02/19 11:48:13.256 +08:00] [WARN] [endpoint.rs:255] ["region not found on incremental scan"] [region_id=48]
[2020/02/19 11:48:13.256 +08:00] [WARN] [endpoint.rs:255] ["region not found on incremental scan"] [region_id=48]
[2020/02/19 11:48:13.257 +08:00] [WARN] [endpoint.rs:255] ["region not found on incremental scan"] [region_id=48]
```

version of tikv: ad59724513ab83461c54c1996f89235301a036d7

the `region not....` log in tikv is filtered
[cdc.tar.gz](https://github.com/pingcap/ticdc/files/4248604/cdc.tar.gz)
[issue268.tar.gz](https://github.com/pingcap/ticdc/files/4248605/issue268.tar.gz)

**Comment by 5kbpers** [comment] 2020-02-25 12:18
I found this bug is probably caused by two reasons:
1. tikv does not check if the peer is leader
2. tikv does not return instantly after it checks epoch not matched

**Comment by 5kbpers** [comment] 2020-03-02 13:13
Already fixed in https://github.com/tikv/tikv/pull/6691

**Closed** 2020-03-16 02:55 UTC
Labels: C: TiKV, P1
