### ISSUE TITLE
[CDC 5.3.0] TPCC worklod: one of table has data inconsistency 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#3265] opened 2021-11-04 04:01 UTC
### What did you do?

Test infra case: basic_incremental_sync
-  Create a changefeed
-  Stop the changefeed
-  Run workload: tpcc prepare then run
-  Resume the changefeed
-  Wait workload finish
-  Check if data consistency

### What did you expect to see?

data consistency

### What did you see instead?

data inconsistency in table "new_order", other tables are data consistency.
test logs:
 source and sink have different crc32
 size  
 {"source{"customer":"1071810941","district":"866659896","finishmark":"0","history":"634447754","item":"1126873918",**"new_order":"984054953"**,"order_line":"2609026813","orders":"3956004457","stock":"2974894350","warehouse":"4013458029"}, 
"sink{"customer":"1071810941","district":"866659896","finishmark":"0","item":"1126873918",**"new_order":"1184831743",**"order_line":"2609026813","orders":"3956004457","stock":"2974894350","warehouse":"4013458029"}}

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.3.0
```

TiCDC version (execute `cdc version`):

```console
5.3.0
```

**Comment by Tammyxia** [comment] 2021-11-04 05:29
testbed logs located in here:
http://minio.pingcap.net:9000/minio/test-infra-testground/archive/cdc-testbed--tps-360304-1-497/

**Comment by Tammyxia** [comment] 2021-11-04 05:29
test logs:
http://172.16.4.180:31714/workflows/testground/plan-exec-360304?tab=workflow&nodeId=plan-exec-360304-1991493706&sidePanel=logs

**Comment by amyangfei** [comment] 2021-11-04 08:53
No clear detail to locate the root cause, the ticdc logs are normal. Wait the bug to be reproduced and check data mvcc version.

**Comment by Tammyxia** [comment] 2021-11-05 06:59
Reproduced in case tikv_unavailable_sync: consistency/crc32.go:140        source and sink have different crc32
 size   {"source": {"customer":"3033758127","district":"2057952776","finishmark":"0","history":"2512223096","item":"1975563769",**"new
_order":"3237898306",**"order_line":"1041127509","orders":"116963829","stock":"2199232397","warehouse":"3643357326"}, "sink": {"custom
er":"3033758127","district":"2057952776","finishmark":"0","item":"1975563769",**"new_order":"2449053570"**,"order_line":"1041127509","or
ders":"116963829","stock":"2199232397","warehouse":"3643357326"}}

**Comment by Tammyxia** [comment] 2021-11-09 02:57
This delete sql is not synced to downstream while executed in upstream tidb from genera log: [sql="DELETE FROM new_order WHERE (no_w_id, no_d_id, no_o_id) IN (  (?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?) ) [arguments: (4, 1, 2106, 4, 2, 2106, 4, 3, 2106, 4, 4, 2106, 4, 5, 2106, 4, 6, 2106, 4, 7, 2106, 4, 8, 2106, 4, 9, 2106, 4, 10, 2106)]"]

**Comment by overvenus** [comment] 2021-11-10 08:39
Data lost is fixed by https://github.com/tikv/tikv/pull/11314, change to severity/major, as it is still unknown why only `new_order` table loses data.

**Comment by hicqu** [comment] 2021-12-15 03:28
The bug is introduced by https://github.com/tikv/tikv/pull/11152, which can cause cdc lost old values. tiv/tikv#11134 fixes it by disable the `hint_min_ts` enhancement.

**Closed** 2021-12-15 03:28 UTC
Labels: type/bug, subject/correctness, severity/major, found/automation, area/ticdc
